#!/usr/bin/env python
import chemcoord as cc
import argparse


def read_input():
    # Calling parser for reading filename
    parser = argparse.ArgumentParser(
        description=
        """
        This script takes a zmat file and transforms it to cartesian coordinates.
        """
        )
    parser.add_argument("inputfile", type=str,
            help = "Name of the inputfile.")
    parser.add_argument("--outputfile", type=str,
            help = (
                """
                Name of the outputfile. 
                If None is given it takes then name of the inputfile without fileending and appends .zmat
                """
                ),
            default = None
            )

    args = parser.parse_args()
    return args


args = read_input()

ref_zmat = cc.read.xyz(args.inputfile)
xyz = cc.zmat_functions.zmat_to_xyz(ref_zmat)

if args.outputfile is None:
    outputfile = ''.join(args.inputfile.split('.')[:-1]) + '.xyz'
else:
    outputfile = args.outputfile

cc.write.xyz(zmat, outputfile)
